### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by johnmesh** [s4kibs4mi/play-angular2-java-seed#1]
i am trying to compile this project on windows using "sbt run" command but i keep getting this error message.

java.io.IOException: Cannot run program "npm" (in directory "S:\play-angular2-java-seed-master\ui"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.io.IOException: Cannot run program "npm" (in directory "S:\play-angular2-java-seed-master\ui"): CreateProcess error=2, The system cannot find the file specified
[error] Total time: 0 s, completed Sep 1, 2017 2:59:17 PM

**Comment by s4kibs4mi** [comment]
@johnmesh so far npm is not installed or configured on the system correctly.

**Comment by johnmesh** [comment]
@s4kibs4mi i had already installed the latest npm on my system...currently its v5.3.0

**Comment by johnmesh** [comment]
it worked finally. i forgot to  prefix "npm install" command with "cmd /c" in UIBuild.scala file.
